# Site settings
title: elementary OS
email: timbog80@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  elementary OS Tips & Tricks
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

paginate: 2

#Jekyll website
jekyll: "http://jekyllrb.com/"

# Build settings
markdown: kramdown