# Site settings
title: Elementary OS
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome To Elementary OS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timbog80.github.io" # the base hostname & protocol for your site

#Jekyll website
jekyll: "http://jekyllrb.com/"

# Build settings
markdown: kramdown
